# syntax=docker/dockerfile:1.4.2

FROM wrf_intermediate:latest


###############################################################################
## Install WRF v4.3.3

WORKDIR $WRF_SOURCES

ARG TARGET_URL=https://github.com/wrf-model/WRF/archive/v4.3.3.tar.gz 
ARG TARGET=WRF
ARG EXTRA_FLAGS=

RUN <<EOF_WRF
mkdir $TARGET
cd $TARGET

wget -c $TARGET_URL -O $TARGET.tar.gz
mkdir $TARGET-src
tar -xf $TARGET.tar.gz -C $TARGET-src --strip-components=1

cd $TARGET-src
printf '34\n1\n' | ./configure $EXTRA_FLAGS
./compile em_real
EOF_WRF

ARG WRF_DIR=$WRF_SOURCES/$TARGET/$TARGET-src

###############################################################################
## Install WPS

WORKDIR $WRF_SOURCES

ARG TARGET_URL=https://github.com/wrf-model/WPS/archive/refs/tags/v4.3.1.tar.gz
ARG TARGET=WPS
ARG EXTRA_FLAGS=

RUN <<EOF_WPS
mkdir $TARGET
cd $TARGET

wget -c $TARGET_URL -O $TARGET.tar.gz
mkdir $TARGET-src
tar -xf $TARGET.tar.gz -C $TARGET-src --strip-components=1

cd $TARGET-src
printf '3\n' | ./configure $EXTRA_FLAGS
./compile $EXTRA_FLAGS
EOF_WPS

###############################################################################
## Install WRFPLUS 

WORKDIR $WRF_SOURCES

ARG TARGET_URL=https://github.com/wrf-model/WRF/archive/v4.3.3.tar.gz 
ARG TARGET=WRFPLUS
ARG EXTRA_FLAGS=wrfplus

RUN <<EOF_WRFPLUS
mkdir $TARGET
cd $TARGET
wget -c $TARGET_URL -O $TARGET.tar.gz
mkdir $TARGET-src
tar -xf $TARGET.tar.gz -C $TARGET-src --strip-components=1

cd $TARGET-src
printf '18\n' | ./configure $EXTRA_FLAGS
./compile $EXTRA_FLAGS

EOF_WRFPLUS

ARG WRFPLUS_DIR=$WRF_PREFIX/$TARGET


###############################################################################
## Install WPSPLUS 4DVAR

WORKDIR $WRF_SOURCES

ARG TARGET_URL=https://github.com/wrf-model/WRF/archive/v4.3.3.tar.gz 
ARG TARGET=WRFPLUS_4D
ARG EXTRA_FLAGS=

RUN <<EOF_WRF4DVAR
mkdir $TARGET
cd $TARGET

wget -c $TARGET_URL -O $TARGET.tar.gz
mkdir $TARGET-src
tar -xf $TARGET.tar.gz -C $TARGET-src --strip-components=1

cd $TARGET-src
printf '18\n' | ./configure 4dvar
./compile all_wrfvar

EOF_WRF4DVAR

###############################################################################
## Return to main directory

WORKDIR /