# syntax=docker/dockerfile:1.4.2

FROM ghcr.io/uomresearchit/wrf-libraries as wrf_wps_build


###############################################################################
## Install WRF v4.3.3

WORKDIR $WRF_SOURCES

ARG TARGET_URL=https://github.com/wrf-model/WRF/archive/v4.3.3.tar.gz 
ARG TARGET=WRF
ARG EXTRA_FLAGS=

RUN <<EOF_WRF
mkdir $TARGET
cd $TARGET

wget -c $TARGET_URL -O $TARGET.tar.gz
mkdir $TARGET-src
tar -xf $TARGET.tar.gz -C $TARGET-src --strip-components=1
rm $TARGET.tar.gz

cd $TARGET-src
printf '34\n1\n' | ./configure $EXTRA_FLAGS
./compile em_real

rm run/*exe
EOF_WRF

ARG WRF_DIR=$WRF_SOURCES/$TARGET/$TARGET-src

###############################################################################
## Install WPS

WORKDIR $WRF_SOURCES

ARG TARGET_URL=https://github.com/wrf-model/WPS/archive/refs/tags/v4.3.1.tar.gz
ARG TARGET=WPS
ARG EXTRA_FLAGS=

ADD WPS-nocolon.patch /WRF-SOURCES/WPS-nocolon.patch

RUN <<EOF_WPS
DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y patch 
mkdir $TARGET
cd $TARGET

wget -c $TARGET_URL -O $TARGET.tar.gz
mkdir $TARGET-src
tar -xf $TARGET.tar.gz -C $TARGET-src --strip-components=1
rm $TARGET.tar.gz

cd $TARGET-src
patch -p1 < /WRF-SOURCES/WPS-nocolon.patch
printf '3\n' | ./configure $EXTRA_FLAGS
./compile $EXTRA_FLAGS
EOF_WPS

################################################################################

FROM ghcr.io/uomresearchit/wrf-libraries as wrf_final

COPY --from=wrf_wps_build /WRF-SOURCES/WPS/WPS-src/ /WPS-run
COPY --from=wrf_wps_build /WRF-SOURCES/WPS/WPS-src/*exe /usr/local/bin/
COPY --from=wrf_wps_build /WRF-SOURCES/WRF/WRF-src/main/*exe /usr/local/bin/
COPY --from=wrf_wps_build /WRF-SOURCES/WRF/WRF-src/run /WRF-run


LABEL version.wrf=4.3.3
LABEL org.opencontainers.image.description="WRF and WPS executables and run directories"
LABEL org.opencontainers.image.source="https://github.com/UoMResearchIT/wrf-docker"


WORKDIR /