# syntax=docker/dockerfile:1.4.2

FROM ubuntu:20.04 AS base_img

###############################################################################
## Install requirements

RUN apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC \
                      apt-get install -y \ 
                                      wget \
                                      gcc \
                                      gfortran \                            
                                      g++ \                                 
                                      libtool \
                                      automake \
                                      autoconf \
                                      make \
                                      m4 \
                                      csh \
                                      zip \
                                      cmake \
                                      python3

###############################################################################
## Set directory variables

ENV WRF_SOURCES=/WRF-SOURCES
ENV WRF_PREFIX=/usr/local
ENV WRF_LIB=$WRF_PREFIX/lib
ENV WRF_INC=$WRF_PREFIX/include

ENV LD_LIBRARY_PATH=$WRF_LIB

## create working directory, and change to this location
WORKDIR $WRF_SOURCES


###############################################################################
## Install zlib v1.2.11

FROM base_img AS zlib_build

WORKDIR $WRF_SOURCES

ARG TARGET_URL=https://github.com/madler/zlib/archive/refs/tags/v1.2.11.tar.gz
ARG TARGET=zlib
ARG EXTRA_FLAGS=

RUN <<EOF_ZLIB
mkdir $TARGET
cd $TARGET

wget -c $TARGET_URL -O $TARGET.tar.gz
mkdir $TARGET-src
tar -xf $TARGET.tar.gz -C $TARGET-src --strip-components=1

mkdir $TARGET-build
cd $TARGET-build

../$TARGET-src/configure $EXTRA_FLAGS
make -j$(nproc)
make install

cd $WRF-SOURCES
rm -rf $TARGET
EOF_ZLIB


###############################################################################
## Install libpng

FROM base_img AS libpng_build

COPY --from=zlib_build ./usr/local/. /usr/local/

WORKDIR $WRF_SOURCES

ARG TARGET_URL=https://download.sourceforge.net/libpng/libpng-1.6.37.tar.gz
ARG TARGET=libpng
ARG EXTRA_FLAGS=

RUN <<EOF_LIBPNG
mkdir $TARGET
cd $TARGET

wget -c $TARGET_URL -O $TARGET.tar.gz
mkdir $TARGET-src
tar -xf $TARGET.tar.gz -C $TARGET-src --strip-components=1

mkdir $TARGET-build
cd $TARGET-build

../$TARGET-src/configure --prefix=$WRF_PREFIX $EXTRA_FLAGS
make -j$(nproc) && \
make install

cd $WRF-SOURCES
rm -rf $TARGET
EOF_LIBPNG

###############################################################################
## Install JasPer

FROM base_img AS jasper_build

WORKDIR $WRF_SOURCES

ARG TARGET_URL=https://github.com/jasper-software/jasper/releases/download/version-2.0.33/jasper-2.0.33.tar.gz
ARG TARGET=jasper
ARG EXTRA_FLAGS=

RUN <<EOF_JASPER
mkdir $TARGET
cd $TARGET

wget -c $TARGET_URL -O $TARGET.tar.gz
mkdir $TARGET-src
tar -xf $TARGET.tar.gz -C $TARGET-src --strip-components=1

mkdir $TARGET-build
cd $TARGET-build
cmake -DJAS_ENABLED_SHARED=true -DJAS_ENABLE_LIBJPEG=true ../$TARGET-src/
make -j$(nproc)
make install

cd $WRF-SOURCES
rm -rf $TARGET
EOF_JASPER

ENV JASPERLIB=$WRF_LIB
ENV JASPERINC=$WRF_INC

###############################################################################
## Install hdf5

FROM base_img AS netcdf_build

COPY --from=zlib_build ./usr/local/. /usr/local/

WORKDIR $WRF_SOURCES

ARG TARGET_URL=https://github.com/HDFGroup/hdf5/archive/refs/tags/hdf5-1_13_1.tar.gz
ARG TARGET=hdf5
ARG EXTRA_FLAGS="--enable-hl --enable-fortran"

RUN <<EOF_HDF5
mkdir $TARGET
cd $TARGET

wget -c $TARGET_URL -O $TARGET.tar.gz
mkdir $TARGET-src
tar -xf $TARGET.tar.gz -C $TARGET-src --strip-components=1

mkdir $TARGET-build
cd $TARGET-build
../$TARGET-src/configure --prefix=$WRF_PREFIX $EXTRA_FLAGS
make -j$(nproc)
make install

cd $WRF-SOURCES
rm -rf $TARGET 
EOF_HDF5

ENV HDF5=$WRF_PREFIX

###############################################################################
## Install NETCDF C library


WORKDIR $WRF_SOURCES

ARG TARGET_URL=https://github.com/Unidata/netcdf-c/archive/refs/tags/v4.8.1.tar.gz
ARG TARGET=netcdf-c
ARG EXTRA_FLAGS=--disable-dap

RUN <<EOF_NETC
mkdir $TARGET
cd $TARGET

wget -c $TARGET_URL -O $TARGET.tar.gz
mkdir $TARGET-src
tar -xf $TARGET.tar.gz -C $TARGET-src --strip-components=1

mkdir $TARGET-build
cd $TARGET-build
../$TARGET-src/configure --prefix=$WRF_PREFIX $EXTRA_FLAGS
make -j$(nproc)
make install

cd $WRF-SOURCES
rm -rf $TARGET
EOF_NETC

###############################################################################
## Install NETCDF Fortran library

WORKDIR $WRF_SOURCES

ARG TARGET_URL=https://github.com/Unidata/netcdf-fortran/archive/refs/tags/v4.5.4.tar.gz
ARG TARGET=netcdf-fortran
ARG EXTRA_FLAGS=--disable-shared

RUN <<EOF_NETF
mkdir $TARGET
cd $TARGET

wget -c $TARGET_URL -O $TARGET.tar.gz
mkdir $TARGET-src
tar -xf $TARGET.tar.gz -C $TARGET-src --strip-components=1

mkdir $TARGET-build
cd $TARGET-build
../$TARGET-src/configure --prefix=$WRF_PREFIX $EXTRA_FLAGS
make -j$(nproc)
make install

cd $WRF-SOURCES
rm -rf $TARGET
EOF_NETF


###############################################################################
## Install MPICH

FROM base_img AS mpich_build



WORKDIR $WRF_SOURCES

ARG TARGET_URL=https://github.com/pmodels/mpich/releases/download/v4.0.2/mpich-4.0.2.tar.gz
ARG TARGET=mpich
ARG EXTRA_FLAGS=--with-device=ch3

RUN <<EOF_MPICH
mkdir $TARGET
cd $TARGET

wget -c $TARGET_URL -O $TARGET.tar.gz
mkdir $TARGET-src
tar -xf $TARGET.tar.gz -C $TARGET-src --strip-components=1

mkdir $TARGET-build
cd $TARGET-build
../$TARGET-src/configure --prefix=$WRF_PREFIX $EXTRA_FLAGS
make -j$(nproc)
make install

cd $WRF-SOURCES
rm -rf $TARGET 
EOF_MPICH

###############################################################################
## general arguments

FROM base_img as final

COPY --from=libpng_build ./usr/local/. /usr/local/
COPY --from=jasper_build ./usr/local/. /usr/local/
#COPY --from=mpich_build ./usr/local/. /usr/local/


ENV JASPER_INC=$WRF_PREFIX/include
ENV PNG_INC=$WRF_PREFIX/include
ENV NETCDF=$WRF_PREFIX/


###############################################################################
## Return to main directory

WORKDIR /