# syntax=docker/dockerfile:1.4.2

FROM ghcr.io/uomresearchit/wrf-libraries


###############################################################################
## Install WRFPLUS 4DVAR

WORKDIR $WRF_SOURCES

ARG TARGET_URL=https://github.com/wrf-model/WRF/archive/v4.3.3.tar.gz 
ARG TARG_PLUS=WRFPLUS
ARG TARGET=WRF4DVAR

ARG WRFPLUS_DIR=$WRF_SOURCES/$TARG_PLUS

RUN <<EOF_WRF4DVAR
mkdir $TARGET
wget -c $TARGET_URL -O $TARGET.tar.gz
tar -xf $TARGET.tar.gz -C $TARGET --strip-components=1
rm $TARGET.tar.gz

cp -a $TARGET $TARG_PLUS

cd $TARG_PLUS
# compile WRFPLUS
printf '18\n' | ./configure wrfplus
./compile wrfplus

cd ../$TARGET
# compile WRF4DVAR
printf '18\n' | ./configure 4dvar
./compile all_wrfvar

# move generated binaries to /usr/local/bin/
cd ..
mv $TARG_PLUS/main/wrfplus.exe /usr/local/bin/
mv $TARGET/var/build/*exe $TARGET/var/obsproc/*exe /usr/local/bin/

# remove build directories
rm -rf $TARG_PLUS
rm -rf $TARGET

EOF_WRF4DVAR

###############################################################################
## Return to main directory

LABEL version.wrf=4.3.3
LABEL org.opencontainers.image.description="WRF-Plus and WRF-4DVAR executables"
LABEL org.opencontainers.image.source="https://github.com/UoMResearchIT/wrf-docker"


WORKDIR /